# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TARGET = tisaNET_NetViewer
DESTDIR = ../x64/Release
CONFIG += release
DEFINES += TISANET_NETVIEWER_LIB
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += release
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(tisaNET_NetViewer.pri)
